[ids]
*

[main]
space = overload(layer, space)
f = overloadi(f, overload2(shift, f, 200), 150)
d = overloadi(d, overload2(control, d, 200), 150)

[layer]
a = tab
g = t
h = y
l = [
; = ]

n = backspace
b = enter
